FROM node:16-alpine AS builder
COPY . /app
WORKDIR /app
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_LOCATION_API_KEY
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG VERSION
RUN npm ci
RUN npm run build

FROM node:16-alpine
COPY --from=builder /app /app
WORKDIR /app
ENV PORT=3000
EXPOSE 3000
CMD [ "npm", "start" ]
