import type { NextPage } from 'next'
import Head from 'next/head'
import { Title } from '../styles'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Title>My page</Title>
			</main>

			<footer></footer>
		</>
	)
}

export default Home
